name: agat_env
channels:
  - defaults
  - conda-forge
  - bioconda
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - _r-mutex=1.0.1=anacondar_1
  - agat=1.5.1=pl5321hdfd78af_0
  - alsa-lib=1.2.15.1=hb03c661_0
  - attr=2.5.2=h39aace5_0
  - binutils_impl_linux-64=2.45=default_hfdba357_105
  - bwidget=1.10.1=ha770c72_1
  - bzip2=1.0.8=hda65f42_8
  - c-ares=1.34.6=hb03c661_0
  - ca-certificates=2025.11.12=hbd8a1cb_0
  - cairo=1.18.4=h3394656_0
  - curl=8.17.0=h4e3cde8_1
  - cyrus-sasl=2.1.28=hd9c7081_0
  - dbus=1.13.6=h5008d03_3
  - expat=2.7.3=hecca717_0
  - fastx_toolkit=0.0.14=h503566f_13
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=h77eed37_3
  - fontconfig=2.15.0=h7e30c49_1
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=hc364b38_1
  - freetype=2.14.1=ha770c72_0
  - fribidi=1.0.16=hb03c661_0
  - gcc_impl_linux-64=15.2.0=hc5723f1_16
  - gfortran_impl_linux-64=15.2.0=h281d09f_16
  - glib=2.84.1=h07242d1_0
  - glib-tools=2.84.1=h4833e2c_0
  - gnuplot=5.4.10=hb1719d7_0
  - graphite2=1.3.14=hecca717_2
  - gsl=2.7=he838d99_0
  - gst-plugins-base=1.24.11=h651a532_0
  - gstreamer=1.24.11=hc37bda9_0
  - gxx_impl_linux-64=15.2.0=hda75c37_16
  - harfbuzz=11.2.1=h3beb420_0
  - htslib=1.23=h566b1c6_0
  - icu=75.1=he02047a_0
  - kernel-headers_linux-64=5.14.0=he073ed8_3
  - keyutils=1.6.3=hb9d3cd8_0
  - krb5=1.21.3=h659f571_0
  - lame=3.100=h166bdaf_1003
  - ld_impl_linux-64=2.45=default_hbd61a6d_105
  - lerc=4.0.0=h0aef613_1
  - libblas=3.11.0=5_h4a7cf45_openblas
  - libcap=2.77=h3ff7636_0
  - libcblas=3.11.0=5_h0358290_openblas
  - libclang-cpp20.1=20.1.8=default_h99862b1_5
  - libclang13=21.1.0=default_h746c552_1
  - libcups=2.3.3=hb8b1518_5
  - libcurl=8.17.0=h4e3cde8_1
  - libdb=6.2.32=h9c3ff4c_0
  - libdeflate=1.22=hb9d3cd8_0
  - libdrm=2.4.125=hb03c661_1
  - libedit=3.1.20250104=pl5321h7949ede_0
  - libegl=1.7.0=ha4b6fd6_2
  - libev=4.33=hd590300_2
  - libevent=2.1.12=hf998b51_1
  - libexpat=2.7.3=hecca717_0
  - libffi=3.4.6=h2dba641_1
  - libflac=1.5.0=he200343_1
  - libfreetype=2.14.1=ha770c72_0
  - libfreetype6=2.14.1=h73754d4_0
  - libgcc=15.2.0=he0feb66_16
  - libgcc-devel_linux-64=15.2.0=hcc6f6b0_116
  - libgcc-ng=15.2.0=h69a702a_16
  - libgd=2.3.3=h6f5c62b_11
  - libgfortran=15.2.0=h69a702a_16
  - libgfortran-ng=15.2.0=h69a702a_16
  - libgfortran5=15.2.0=h68bc16d_16
  - libgl=1.7.0=ha4b6fd6_2
  - libglib=2.84.1=h2ff4ddf_0
  - libglvnd=1.7.0=ha4b6fd6_2
  - libglx=1.7.0=ha4b6fd6_2
  - libgomp=15.2.0=he0feb66_16
  - libgtextutils=0.7=h503566f_14
  - libiconv=1.18=h3b78370_2
  - libjpeg-turbo=3.1.2=hb03c661_0
  - liblapack=3.11.0=5_h47877c9_openblas
  - libllvm20=20.1.8=hecd9e04_0
  - libllvm21=21.1.0=hecd9e04_0
  - liblzma=5.8.1=hb9d3cd8_2
  - libmpdec=4.0.0=hb9d3cd8_0
  - libnghttp2=1.67.0=had1ee68_0
  - libntlm=1.8=hb9d3cd8_0
  - libogg=1.3.5=hd0c01bc_1
  - libopenblas=0.3.30=pthreads_h94d23a6_4
  - libopus=1.6=h0fd0de7_0
  - libpciaccess=0.18=hb9d3cd8_0
  - libpng=1.6.53=h421ea60_0
  - libpq=17.7=h5c52fec_1
  - libsanitizer=15.2.0=h90f66d4_16
  - libsndfile=1.2.2=hc7d488a_2
  - libsqlite=3.51.1=h0c1763c_1
  - libssh2=1.11.1=hcf80075_0
  - libstdcxx=15.2.0=h934c35e_16
  - libstdcxx-devel_linux-64=15.2.0=hd446a21_116
  - libstdcxx-ng=15.2.0=hdf11a46_16
  - libsystemd0=258.3=h6569c3e_0
  - libtiff=4.7.0=hc4654cb_2
  - libuuid=2.41.3=h5347b49_0
  - libvorbis=1.3.7=h54a6638_2
  - libwebp-base=1.6.0=hd42ef1d_0
  - libxcb=1.17.0=h8a09558_0
  - libxcrypt=4.4.36=hd590300_1
  - libxkbcommon=1.11.0=he8b52b9_0
  - libxml2=2.13.9=h04c0eec_0
  - libzlib=1.3.1=hb9d3cd8_2
  - make=4.4.1=hb9d3cd8_2
  - mpg123=1.32.9=hc50e24c_0
  - ncurses=6.5=h2d0b736_3
  - nspr=4.38=h29cc59b_0
  - nss=3.118=h445c969_0
  - openldap=2.6.10=he970967_0
  - openssl=3.6.0=h26f9b46_0
  - packaging=25.0=pyh29332c3_1
  - pango=1.56.3=h9ac818e_1
  - pcre2=10.44=hc749103_2
  - perl=5.32.1=7_hd590300_perl5
  - perl-b-cow=0.007=pl5321hb9d3cd8_1
  - perl-b-hooks-endofscope=0.28=pl5321ha770c72_1
  - perl-base=2.23=pl5321hd8ed1ab_0
  - perl-bioperl-core=1.7.8=pl5321hdfd78af_1
  - perl-business-isbn=3.007=pl5321hd8ed1ab_0
  - perl-business-isbn-data=20210112.006=pl5321hd8ed1ab_0
  - perl-carp=1.50=pl5321hd8ed1ab_0
  - perl-class-inspector=1.36=pl5321hdfd78af_0
  - perl-class-load=0.25=pl5321ha770c72_2
  - perl-class-load-xs=0.10=pl5321hb9d3cd8_0
  - perl-class-methodmaker=2.25=pl5321h7b50bb2_1
  - perl-clone=0.46=pl5321hb9d3cd8_1
  - perl-compress-raw-bzip2=2.214=pl5321hda65f42_0
  - perl-compress-raw-zlib=2.214=pl5321h4dac143_0
  - perl-constant=1.33=pl5321hd8ed1ab_0
  - perl-cpan-meta-check=0.014=pl5321ha770c72_0
  - perl-data-dump=1.25=pl5321h7b50bb2_2
  - perl-data-optlist=0.114=pl5321ha770c72_1
  - perl-db_file=1.858=pl5321hb9d3cd8_0
  - perl-devel-globaldestruction=0.14=pl5321ha770c72_0
  - perl-devel-overloadinfo=0.007=pl5321ha770c72_1
  - perl-devel-stacktrace=2.04=pl5321h296ab09_0
  - perl-digest-hmac=1.05=pl5321hdfd78af_0
  - perl-digest-md5=2.59=pl5321hb9d3cd8_3
  - perl-dist-checkconflicts=0.11=pl5321ha770c72_0
  - perl-encode=3.21=pl5321hb9d3cd8_1
  - perl-encode-locale=1.05=pl5321hdfd78af_7
  - perl-eval-closure=0.14=pl5321ha770c72_0
  - perl-exporter=5.74=pl5321hd8ed1ab_0
  - perl-exporter-tiny=1.002002=pl5321hd8ed1ab_0
  - perl-extutils-makemaker=7.70=pl5321hd8ed1ab_0
  - perl-file-listing=6.16=pl5321hdfd78af_0
  - perl-file-pushd=1.016=pl5321ha770c72_0
  - perl-file-share=0.25=pl5321hdfd78af_3
  - perl-file-sharedir=1.118=pl5321hdfd78af_0
  - perl-file-sharedir-install=0.14=pl5321hdfd78af_0
  - perl-file-spec=3.48_01=pl5321hdfd78af_2
  - perl-gd=2.83=pl5321hc25ab4d_0
  - perl-gdgraph=1.56=pl5321hdfd78af_0
  - perl-gdgraph-histogram=1.1=pl5321hdfd78af_4
  - perl-gdtextutil=0.86=pl5321h7b50bb2_9
  - perl-getopt-long=2.58=pl5321hdfd78af_0
  - perl-graph=0.9735=pl5321hdfd78af_0
  - perl-heap=0.80=pl5321hdfd78af_1
  - perl-html-parser=3.81=pl5321h4ac6f70_1
  - perl-html-tagset=3.24=pl5321hdfd78af_0
  - perl-http-cookiejar-lwp=0.014=pl5321hdfd78af_0
  - perl-http-cookies=6.11=pl5321hdfd78af_0
  - perl-http-daemon=6.16=pl5321hdfd78af_0
  - perl-http-date=6.06=pl5321hdfd78af_0
  - perl-http-message=7.01=pl5321hdfd78af_0
  - perl-http-negotiate=6.01=pl5321hdfd78af_4
  - perl-inc-latest=0.500=pl5321ha770c72_0
  - perl-io-html=1.004=pl5321hdfd78af_0
  - perl-io-socket-ssl=2.075=pl5321hd8ed1ab_0
  - perl-io-tty=1.20=pl5321hb9d3cd8_3
  - perl-ipc-run=20250809.0=pl5321hdfd78af_0
  - perl-libwww-perl=6.81=pl5321hdfd78af_0
  - perl-list-moreutils=0.430=pl5321hdfd78af_0
  - perl-list-moreutils-xs=0.430=pl5321h7b50bb2_5
  - perl-lwp-mediatypes=6.04=pl5321hdfd78af_1
  - perl-lwp-protocol-https=6.14=pl5321hdfd78af_1
  - perl-mime-base64=3.16=pl5321hb9d3cd8_3
  - perl-module-build=0.4234=pl5321ha770c72_1
  - perl-module-implementation=0.09=pl5321ha770c72_1
  - perl-module-load=0.34=pl5321hdfd78af_0
  - perl-module-runtime=0.016=pl5321ha770c72_1
  - perl-module-runtime-conflicts=0.003=pl5321ha770c72_0
  - perl-moose=2.2207=pl5321hb9d3cd8_2
  - perl-mozilla-ca=20250602=pl5321hdfd78af_0
  - perl-mro-compat=0.15=pl5321ha770c72_0
  - perl-namespace-clean=0.27=pl5321h296ab09_1
  - perl-net-http=6.24=pl5321hdfd78af_0
  - perl-net-ssleay=1.94=pl5321hf672d98_1
  - perl-ntlm=1.09=pl5321hdfd78af_5
  - perl-package-deprecationmanager=0.18=pl5321ha770c72_2
  - perl-package-stash=0.40=pl5321ha770c72_2
  - perl-package-stash-xs=0.30=pl5321hb9d3cd8_2
  - perl-params-util=1.102=pl5321hb9d3cd8_1
  - perl-parent=0.243=pl5321hd8ed1ab_0
  - perl-perlio-gzip=0.20=pl5321h577a1d6_7
  - perl-pod-escapes=1.07=pl5321hdfd78af_2
  - perl-regexp-common=2017060201=pl5321hd8ed1ab_0
  - perl-safe=2.37=pl5321hdfd78af_2
  - perl-scalar-list-utils=1.70=pl5321hb03c661_0
  - perl-set-object=1.43=pl5321h7b50bb2_0
  - perl-socket=2.027=pl5321h5c03b87_6
  - perl-sort-naturally=1.03=pl5321hdfd78af_3
  - perl-statistics-r=0.34=pl5321r44hdfd78af_7
  - perl-storable=3.15=pl5321hb9d3cd8_2
  - perl-sub-exporter=0.991=pl5321ha770c72_1
  - perl-sub-exporter-progressive=0.001013=pl5321ha770c72_0
  - perl-sub-identify=0.14=pl5321hb9d3cd8_2
  - perl-sub-install=0.928=pl5321hd8ed1ab_0
  - perl-sub-name=0.28=pl5321hb9d3cd8_1
  - perl-term-progressbar=2.23=pl5321hdfd78af_0
  - perl-test=1.26=pl5321hd8ed1ab_0
  - perl-test-cleannamespaces=0.24=pl5321ha770c72_2
  - perl-test-fatal=0.016=pl5321ha770c72_0
  - perl-test-harness=3.44=pl5321hd8ed1ab_0
  - perl-test-leaktrace=0.17=pl5321h7bf1ee8_1
  - perl-test-needs=0.002009=pl5321hd8ed1ab_0
  - perl-test-nowarnings=1.06=pl5321ha770c72_0
  - perl-test-requiresinternet=0.05=pl5321hdfd78af_1
  - perl-test-warnings=0.031=pl5321ha770c72_0
  - perl-text-balanced=2.07=pl5321hdfd78af_0
  - perl-text-wrap=2021.0814=pl5321hd8ed1ab_0
  - perl-time-local=1.35=pl5321hdfd78af_0
  - perl-timedate=2.33=pl5321hdfd78af_2
  - perl-try-tiny=0.31=pl5321ha770c72_0
  - perl-uri=5.34=pl5321ha770c72_0
  - perl-url-encode=0.03=pl5321h9ee0642_1
  - perl-variable-magic=0.64=pl5321hb9d3cd8_0
  - perl-vars=1.03=pl5321hdfd78af_2
  - perl-www-robotrules=6.02=pl5321hdfd78af_4
  - perl-yaml=1.30=pl5321hdfd78af_0
  - pip=25.3=pyh145f28c_0
  - pixman=0.46.4=h54a6638_1
  - pthread-stubs=0.4=hb9d3cd8_1002
  - pulseaudio-client=17.0=hac146a9_1
  - python=3.14.0=h5989046_101_cp314
  - python_abi=3.14=8_cp314
  - qt-main=5.15.15=hea1682b_4
  - r-base=4.4.2=hbab086e_1
  - readline=8.3=h853b02a_0
  - samtools=1.23=h96c455f_0
  - sed=4.9=h6688a6e_0
  - sysroot_linux-64=2.34=h087de78_3
  - tk=8.6.13=noxft_ha0e22de_103
  - tktable=2.10=h8d826fa_7
  - tzdata=2025c=hc9c84f9_1
  - xcb-util=0.4.1=h4f16b4b_2
  - xcb-util-image=0.4.0=hb711507_2
  - xcb-util-keysyms=0.4.1=hb711507_0
  - xcb-util-renderutil=0.3.10=hb711507_0
  - xcb-util-wm=0.4.2=hb711507_0
  - xkeyboard-config=2.46=hb03c661_0
  - xorg-libice=1.1.2=hb9d3cd8_0
  - xorg-libsm=1.2.6=he73a12e_0
  - xorg-libx11=1.8.12=h4f16b4b_0
  - xorg-libxau=1.0.12=hb03c661_1
  - xorg-libxdamage=1.1.6=hb9d3cd8_0
  - xorg-libxdmcp=1.1.5=hb03c661_1
  - xorg-libxext=1.3.6=hb9d3cd8_0
  - xorg-libxfixes=6.0.2=hb03c661_0
  - xorg-libxrender=0.9.12=hb9d3cd8_0
  - xorg-libxshmfence=1.3.3=hb9d3cd8_0
  - xorg-libxt=1.3.1=hb9d3cd8_0
  - xorg-libxxf86vm=1.1.6=hb9d3cd8_0
  - zlib=1.3.1=hb9d3cd8_2
  - zstd=1.5.7=hb78ec9c_6
