name: egapx_qc_env
channels:
  - defaults
  - conda-forge
  - bioconda
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - _r-mutex=1.0.1=anacondar_1
  - adwaita-icon-theme=48.0=unix_0
  - agat=1.4.2=pl5321hdfd78af_1
  - alsa-lib=1.2.13=hb9d3cd8_0
  - annotated-types=0.7.0=pyhd8ed1ab_1
  - argcomplete=3.6.2=pyhd8ed1ab_0
  - at-spi2-atk=2.38.0=h0630a04_3
  - at-spi2-core=2.40.3=h0630a04_0
  - atk-1.0=2.38.0=h04ea711_2
  - augustus=3.5.0=pl5321heb9362c_5
  - bamtools=2.5.2=h077b44d_6
  - bbmap=39.19=he5f24ec_0
  - binutils_impl_linux-64=2.43=h4bf12b8_4
  - biopython=1.85=py39h8cd3c5a_1
  - black=25.1.0=pyha5154f8_0
  - blast=2.16.0=h66d330f_5
  - bleach=6.2.0=pyh29332c3_4
  - boltons=24.0.0=pyhd8ed1ab_1
  - boost-cpp=1.85.0=h3c6214e_4
  - brotli=1.1.0=hb9d3cd8_2
  - brotli-bin=1.1.0=hb9d3cd8_2
  - brotli-python=1.1.0=py39hf88036b_2
  - busco=5.8.3=pyhdfd78af_0
  - bwidget=1.10.1=ha770c72_0
  - bzip2=1.0.8=h4bc722e_7
  - c-ares=1.34.5=hb9d3cd8_0
  - ca-certificates=2025.1.31=hbcca054_0
  - cachecontrol=0.14.2=pyha770c72_0
  - cachecontrol-with-filecache=0.14.2=pyhd8ed1ab_0
  - cairo=1.18.4=h3394656_0
  - cdbtools=0.99=1
  - certifi=2025.1.31=pyhd8ed1ab_0
  - cffi=1.17.1=py39h15c3d72_0
  - charset-normalizer=3.4.1=pyhd8ed1ab_0
  - cheetah3=3.2.6.post2=py39hd1e30aa_4
  - click=8.1.8=pyh707e725_0
  - coloredlogs=15.0.1=pyhd8ed1ab_4
  - conda-package-streaming=0.11.0=pyhd8ed1ab_1
  - contourpy=1.3.0=py39h74842e3_2
  - curl=8.13.0=h332b0f4_0
  - cwl-upgrader=1.2.12=pyhd8ed1ab_0
  - cwl-utils=0.37=pyhbbac1ac_0
  - cwlformat=2022.02.18=pyhd8ed1ab_0
  - cwltool=3.1.20250110105449=py39h78568d8_0
  - cycler=0.12.1=pyhd8ed1ab_1
  - cyrus-sasl=2.1.27=h54b06d7_7
  - dbus=1.13.6=h5008d03_3
  - dendropy=5.0.6=pyhdfd78af_0
  - diamond=2.1.11=h5ca1c30_1
  - docutils=0.21.2=pyhd8ed1ab_1
  - double-conversion=3.3.1=h5888daf_0
  - entrez-direct=22.4=he881be0_0
  - epoxy=1.5.10=h166bdaf_1
  - expat=2.7.0=h5888daf_0
  - filelock=3.18.0=pyhd8ed1ab_0
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=h77eed37_3
  - fontconfig=2.15.0=h7e30c49_1
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=0
  - fonttools=4.57.0=py39h9399b63_0
  - freetype=2.13.3=h48d6fc4_0
  - fribidi=1.0.10=h36c2ea0_0
  - future=1.0.0=pyhd8ed1ab_2
  - galaxy-tool-util=24.1.4=pyhd8ed1ab_0
  - galaxy-util=24.1.4=pyhd8ed1ab_0
  - gawk=5.3.1=hcd3d067_0
  - gcc_impl_linux-64=14.2.0=hdb7739f_2
  - gdk-pixbuf=2.42.12=hb9ae30d_0
  - gfortran_impl_linux-64=14.2.0=h0ee6e4a_2
  - giflib=5.2.2=hd590300_0
  - glib-tools=2.84.1=h4833e2c_0
  - gmp=6.3.0=hac33072_2
  - graphite2=1.3.13=h59595ed_1003
  - graphviz=12.2.1=h5ae0cbf_1
  - gsl=2.7=he838d99_0
  - gtk3=3.24.43=h0c6a113_5
  - gts=0.7.6=h977cf35_4
  - gxx_impl_linux-64=14.2.0=h2ead766_2
  - h2=4.2.0=pyhd8ed1ab_0
  - harfbuzz=11.0.1=h2c12942_0
  - hicolor-icon-theme=0.17=ha770c72_2
  - hmmer=3.1b2=3
  - hpack=4.1.0=pyhd8ed1ab_0
  - htslib=1.21=h566b1c6_1
  - humanfriendly=10.0=pyh707e725_8
  - hyperframe=6.1.0=pyhd8ed1ab_0
  - icu=75.1=he02047a_0
  - idna=3.10=pyhd8ed1ab_1
  - importlib-resources=6.5.2=pyhd8ed1ab_0
  - importlib_resources=6.5.2=pyhd8ed1ab_0
  - isodate=0.7.2=pyhd8ed1ab_1
  - kernel-headers_linux-64=3.10.0=he073ed8_18
  - keyutils=1.6.1=h166bdaf_0
  - kiwisolver=1.4.7=py39h74842e3_0
  - krb5=1.21.3=h659f571_0
  - lcms2=2.17=h717163a_0
  - ld_impl_linux-64=2.43=h712a8e2_4
  - lerc=4.0.0=h27087fc_0
  - libasprintf=0.23.1=h8e693c7_0
  - libblas=3.9.0=31_h59b9bed_openblas
  - libboost=1.85.0=h0ccab89_4
  - libboost-devel=1.85.0=h00ab1b0_4
  - libboost-headers=1.85.0=ha770c72_4
  - libbrotlicommon=1.1.0=hb9d3cd8_2
  - libbrotlidec=1.1.0=hb9d3cd8_2
  - libbrotlienc=1.1.0=hb9d3cd8_2
  - libcblas=3.9.0=31_he106b2a_openblas
  - libclang-cpp20.1=20.1.2=default_hb5137d0_0
  - libclang13=20.1.2=default_h9c6a7e4_0
  - libcups=2.3.3=h4637d8d_4
  - libcurl=8.13.0=h332b0f4_0
  - libdb=6.2.32=h9c3ff4c_0
  - libdeflate=1.23=h4ddbbb0_0
  - libdrm=2.4.124=hb9d3cd8_0
  - libedit=3.1.20250104=pl5321h7949ede_0
  - libegl=1.7.0=ha4b6fd6_2
  - libev=4.33=hd590300_2
  - libexpat=2.7.0=h5888daf_0
  - libffi=3.4.6=h2dba641_1
  - libgcc=14.2.0=h767d61c_2
  - libgcc-devel_linux-64=14.2.0=h9c4974d_102
  - libgcc-ng=14.2.0=h69a702a_2
  - libgd=2.3.3=h6f5c62b_11
  - libgettextpo=0.23.1=h5888daf_0
  - libgfortran=14.2.0=h69a702a_2
  - libgfortran-ng=14.2.0=h69a702a_2
  - libgfortran5=14.2.0=hf1ad2bd_2
  - libgl=1.7.0=ha4b6fd6_2
  - libglib=2.84.1=h2ff4ddf_0
  - libglvnd=1.7.0=ha4b6fd6_2
  - libglx=1.7.0=ha4b6fd6_2
  - libgomp=14.2.0=h767d61c_2
  - libhwloc=2.11.2=default_h0d58e46_1001
  - libiconv=1.18=h4ce23a2_1
  - libidn2=2.3.8=ha4ef2c3_0
  - libjpeg-turbo=3.0.0=hd590300_1
  - liblapack=3.9.0=31_h7ac8fdf_openblas
  - libllvm20=20.1.2=ha7bfdaf_0
  - liblzma=5.8.1=hb9d3cd8_0
  - liblzma-devel=5.8.1=hb9d3cd8_0
  - libnghttp2=1.64.0=h161d5f1_0
  - libnsl=2.0.1=hd590300_0
  - libntlm=1.8=hb9d3cd8_0
  - libopenblas=0.3.29=pthreads_h94d23a6_0
  - libopengl=1.7.0=ha4b6fd6_2
  - libopenssl-static=3.5.0=hb9d3cd8_0
  - libpciaccess=0.18=hd590300_0
  - libpng=1.6.47=h943b412_0
  - libpq=17.4=h27ae623_1
  - librsvg=2.58.4=he92a37e_3
  - libsanitizer=14.2.0=hed042b8_2
  - libsqlite=3.49.1=hee588c1_2
  - libssh2=1.11.1=hf672d98_0
  - libstdcxx=14.2.0=h8f9b012_2
  - libstdcxx-devel_linux-64=14.2.0=h9c4974d_102
  - libstdcxx-ng=14.2.0=h4852527_2
  - libtiff=4.7.0=hd9ff511_3
  - libunistring=0.9.10=h7f98852_0
  - libuuid=2.38.1=h0b41bf4_0
  - libwebp-base=1.5.0=h851e524_0
  - libxcb=1.17.0=h8a09558_0
  - libxcrypt=4.4.36=hd590300_1
  - libxkbcommon=1.8.1=hc4a0caf_0
  - libxml2=2.13.7=h4bc477f_1
  - libxslt=1.1.39=h76b75d6_0
  - libzlib=1.3.1=hb9d3cd8_2
  - lp_solve=5.5.2.11=hd590300_0
  - lxml=5.3.2=py39h3820f57_0
  - make=4.4.1=hb9d3cd8_2
  - markdown-it-py=3.0.0=pyhd8ed1ab_1
  - markupsafe=3.0.2=py39h9399b63_1
  - matplotlib=3.9.4=py39hf3d152e_0
  - matplotlib-base=3.9.4=py39h16632d1_0
  - mdurl=0.1.2=pyhd8ed1ab_1
  - metaeuk=7.bba0d80=pl5321hd6d6fdc_2
  - metis=5.1.0=hd0bcaf9_1007
  - miniprot=0.14=h577a1d6_0
  - mistune=3.0.2=pyhd8ed1ab_1
  - mpfr=4.2.1=h90cbb55_3
  - msgpack-python=1.1.0=py39h74842e3_0
  - munkres=1.1.4=pyh9f0ad1d_0
  - mypy_extensions=1.0.0=pyha770c72_1
  - mysql-common=9.2.0=h266115a_0
  - mysql-connector-c=6.1.11=h659d440_1008
  - mysql-libs=9.2.0=he0572af_0
  - ncbi-vdb=3.2.1=h9948957_0
  - ncurses=6.5=h2d0b736_3
  - networkx=3.2.1=pyhd8ed1ab_0
  - numpy=2.0.2=py39h9cb892a_1
  - openjdk=23.0.2=h53dfc1b_2
  - openjpeg=2.5.3=h5fbd93e_0
  - openldap=2.6.9=he970967_0
  - openssl=3.5.0=h7b32b05_0
  - packaging=24.2=pyhd8ed1ab_2
  - pandas=2.2.3=py39h3b40f6f_2
  - pango=1.56.3=h9ac818e_1
  - pathspec=0.12.1=pyhd8ed1ab_1
  - pcre2=10.44=hba22ea6_2
  - perl=5.32.1=7_hd590300_perl5
  - perl-app-cpanminus=1.7048=pl5321hd8ed1ab_0
  - perl-archive-tar=2.40=pl5321hdfd78af_0
  - perl-b-cow=0.007=pl5321hd590300_0
  - perl-b-hooks-endofscope=0.28=pl5321ha770c72_1
  - perl-base=2.23=pl5321hd8ed1ab_0
  - perl-bioperl-core=1.7.8=pl5321hdfd78af_1
  - perl-business-isbn=3.007=pl5321hd8ed1ab_0
  - perl-business-isbn-data=20210112.006=pl5321hd8ed1ab_0
  - perl-carp=1.50=pl5321hd8ed1ab_0
  - perl-class-inspector=1.36=pl5321hdfd78af_0
  - perl-class-load=0.25=pl5321ha770c72_1
  - perl-class-load-xs=0.10=pl5321hb9d3cd8_0
  - perl-class-method-modifiers=2.13=pl5321ha770c72_0
  - perl-class-methodmaker=2.25=pl5321h7b50bb2_1
  - perl-clone=0.46=pl5321hd590300_0
  - perl-common-sense=3.75=pl5321hd8ed1ab_0
  - perl-compress-raw-bzip2=2.201=pl5321hbf60520_1
  - perl-compress-raw-zlib=2.202=pl5321hadc24fc_0
  - perl-constant=1.33=pl5321hd8ed1ab_0
  - perl-cpan-meta-check=0.014=pl5321ha770c72_0
  - perl-data-dump=1.25=pl5321h7b50bb2_2
  - perl-data-optlist=0.114=pl5321ha770c72_0
  - perl-db_file=1.858=pl5321hb9d3cd8_0
  - perl-dbi=1.643=pl5321hb9d3cd8_1
  - perl-devel-globaldestruction=0.14=pl5321ha770c72_0
  - perl-devel-overloadinfo=0.007=pl5321ha770c72_1
  - perl-devel-stacktrace=2.04=pl5321ha770c72_0
  - perl-digest-hmac=1.04=pl5321hdfd78af_0
  - perl-digest-md5=2.59=pl5321hb9d3cd8_3
  - perl-dist-checkconflicts=0.11=pl5321ha770c72_0
  - perl-encode=3.21=pl5321hb9d3cd8_1
  - perl-encode-locale=1.05=pl5321hdfd78af_7
  - perl-eval-closure=0.14=pl5321ha770c72_0
  - perl-exporter=5.74=pl5321hd8ed1ab_0
  - perl-exporter-tiny=1.002002=pl5321hd8ed1ab_0
  - perl-extutils-makemaker=7.70=pl5321hd8ed1ab_0
  - perl-file-listing=6.16=pl5321hdfd78af_0
  - perl-file-path=2.18=pl5321hd8ed1ab_0
  - perl-file-pushd=1.016=pl5321ha770c72_0
  - perl-file-share=0.25=pl5321hdfd78af_3
  - perl-file-sharedir=1.118=pl5321hdfd78af_0
  - perl-file-sharedir-install=0.13=pl5321hdfd78af_1
  - perl-file-spec=3.48_01=pl5321hdfd78af_2
  - perl-file-temp=0.2304=pl5321hd8ed1ab_0
  - perl-file-which=1.24=pl5321hd8ed1ab_0
  - perl-getopt-long=2.58=pl5321hdfd78af_0
  - perl-graph=0.9735=pl5321hdfd78af_0
  - perl-heap=0.80=pl5321hdfd78af_1
  - perl-html-parser=3.83=pl5321h9948957_0
  - perl-html-tagset=3.20=pl5321hdfd78af_4
  - perl-http-cookies=6.10=pl5321hdfd78af_0
  - perl-http-daemon=6.16=pl5321hdfd78af_0
  - perl-http-date=6.06=pl5321hdfd78af_0
  - perl-http-message=6.36=pl5321hdfd78af_0
  - perl-http-negotiate=6.01=pl5321hdfd78af_4
  - perl-inc-latest=0.500=pl5321ha770c72_0
  - perl-io-compress=2.201=pl5321h503566f_5
  - perl-io-html=1.004=pl5321hdfd78af_0
  - perl-io-socket-ssl=2.075=pl5321hd8ed1ab_0
  - perl-io-tty=1.20=pl5321hb9d3cd8_3
  - perl-io-zlib=1.14=pl5321hdfd78af_0
  - perl-ipc-run=20200505.0=pl5321hdfd78af_0
  - perl-json=4.10=pl5321hdfd78af_1
  - perl-json-xs=4.03=pl5321h9948957_4
  - perl-libwww-perl=6.68=pl5321hdfd78af_0
  - perl-list-moreutils=0.430=pl5321hdfd78af_0
  - perl-list-moreutils-xs=0.430=pl5321h7b50bb2_5
  - perl-lwp-mediatypes=6.04=pl5321hdfd78af_1
  - perl-lwp-protocol-https=6.10=pl5321hdfd78af_0
  - perl-mime-base64=3.16=pl5321hb9d3cd8_2
  - perl-module-build=0.4234=pl5321ha770c72_1
  - perl-module-implementation=0.09=pl5321ha770c72_1
  - perl-module-load=0.34=pl5321hdfd78af_0
  - perl-module-runtime=0.016=pl5321ha770c72_1
  - perl-module-runtime-conflicts=0.003=pl5321ha770c72_0
  - perl-moo=2.005004=pl5321ha770c72_0
  - perl-moose=2.2207=pl5321hb9d3cd8_1
  - perl-mozilla-ca=20211001=pl5321hdfd78af_0
  - perl-mro-compat=0.15=pl5321ha770c72_0
  - perl-namespace-clean=0.27=pl5321h296ab09_1
  - perl-net-http=6.22=pl5321hdfd78af_0
  - perl-net-ssleay=1.94=pl5321hf672d98_0
  - perl-ntlm=1.09=pl5321hdfd78af_5
  - perl-package-deprecationmanager=0.18=pl5321ha770c72_1
  - perl-package-stash=0.40=pl5321ha770c72_1
  - perl-package-stash-xs=0.30=pl5321hb9d3cd8_2
  - perl-parallel-forkmanager=2.03=pl5321hdfd78af_0
  - perl-params-util=1.102=pl5321hb9d3cd8_1
  - perl-parent=0.243=pl5321hd8ed1ab_0
  - perl-pathtools=3.75=pl5321hb9d3cd8_2
  - perl-pod-escapes=1.07=pl5321hdfd78af_2
  - perl-regexp-common=2017060201=pl5321hd8ed1ab_0
  - perl-role-tiny=2.002004=pl5321ha770c72_0
  - perl-safe=2.37=pl5321hdfd78af_2
  - perl-scalar-list-utils=1.69=pl5321hb9d3cd8_0
  - perl-set-object=1.42=pl5321h7b50bb2_5
  - perl-socket=2.027=pl5321h5c03b87_6
  - perl-sort-naturally=1.03=pl5321hdfd78af_3
  - perl-statistics-r=0.34=pl5321r44hdfd78af_7
  - perl-storable=3.15=pl5321hb9d3cd8_2
  - perl-sub-exporter=0.991=pl5321ha770c72_0
  - perl-sub-exporter-progressive=0.001013=pl5321ha770c72_0
  - perl-sub-identify=0.14=pl5321hb9d3cd8_2
  - perl-sub-install=0.928=pl5321hd8ed1ab_0
  - perl-sub-name=0.28=pl5321hb9d3cd8_1
  - perl-sub-quote=2.006006=pl5321ha770c72_0
  - perl-term-progressbar=2.22=pl5321hdfd78af_1
  - perl-test=1.26=pl5321hd8ed1ab_0
  - perl-test-cleannamespaces=0.24=pl5321ha770c72_1
  - perl-test-fatal=0.016=pl5321ha770c72_0
  - perl-test-harness=3.44=pl5321hd8ed1ab_0
  - perl-test-leaktrace=0.17=pl5321h8043a1e_1
  - perl-test-requiresinternet=0.05=pl5321hdfd78af_1
  - perl-test-warnings=0.031=pl5321ha770c72_0
  - perl-text-balanced=2.06=pl5321hdfd78af_0
  - perl-text-wrap=2021.0814=pl5321hd8ed1ab_0
  - perl-time-local=1.35=pl5321hdfd78af_0
  - perl-timedate=2.33=pl5321hdfd78af_2
  - perl-try-tiny=0.31=pl5321ha770c72_0
  - perl-types-serialiser=1.01=pl5321hdfd78af_0
  - perl-uri=5.17=pl5321ha770c72_0
  - perl-url-encode=0.03=pl5321h9ee0642_1
  - perl-variable-magic=0.64=pl5321hd590300_0
  - perl-vars=1.03=pl5321hdfd78af_2
  - perl-www-robotrules=6.02=pl5321hdfd78af_4
  - perl-yaml=1.30=pl5321hdfd78af_0
  - pillow=11.1.0=py39h15c0740_0
  - pip=25.0.1=pyh8b19718_0
  - pixman=0.44.2=h29eaf8c_0
  - platformdirs=4.3.7=pyh29332c3_0
  - prodigal=2.6.3=h7b50bb2_10
  - prov=1.5.1=py_1
  - psutil=7.0.0=py39h8cd3c5a_0
  - pthread-stubs=0.4=hb9d3cd8_1002
  - pycparser=2.22=pyh29332c3_1
  - pydantic=2.11.3=pyh3cfb1c2_0
  - pydantic-core=2.33.1=py39h3506688_0
  - pydot=2.0.0=py39hf3d152e_0
  - pydotplus=2.0.2=pyhd8ed1ab_7
  - pygments=2.19.1=pyhd8ed1ab_0
  - pyparsing=3.2.3=pyhd8ed1ab_1
  - pyside6=6.9.0=py39h0383914_0
  - pysocks=1.7.1=pyha55dd90_7
  - python=3.9.21=h85ef794_2_cpython
  - python-dateutil=2.9.0.post0=pyhff2d567_1
  - python-tzdata=2025.2=pyhd8ed1ab_0
  - python_abi=3.9=6_cp39
  - pytz=2024.1=pyhd8ed1ab_0
  - pyyaml=6.0.2=py39h9399b63_2
  - qhull=2020.2=h434a139_5
  - qt6-main=6.9.0=h6441bc3_1
  - r-base=4.4.3=h9c32bc2_0
  - r-cli=3.6.4=r44h93ab643_1
  - r-colorspace=2.1_1=r44hdb488b9_0
  - r-crayon=1.5.3=r44hc72bb7e_1
  - r-ellipsis=0.3.2=r44hb1dbf0f_3
  - r-fansi=1.0.6=r44hb1dbf0f_1
  - r-farver=2.1.2=r44ha18555a_1
  - r-ggplot2=3.5.2=r44hc72bb7e_0
  - r-glue=1.8.0=r44h2b5f3a1_0
  - r-gtable=0.3.6=r44hc72bb7e_0
  - r-isoband=0.2.7=r44ha18555a_3
  - r-labeling=0.4.3=r44hc72bb7e_1
  - r-lattice=0.22_7=r44h2b5f3a1_0
  - r-lifecycle=1.0.4=r44hc72bb7e_1
  - r-magrittr=2.0.3=r44hb1dbf0f_3
  - r-mass=7.3_64=r44h2b5f3a1_0
  - r-matrix=1.7_3=r44h2ae2be5_0
  - r-mgcv=1.9_3=r44h2ae2be5_0
  - r-munsell=0.5.1=r44hc72bb7e_1
  - r-nlme=3.1_168=r44hb67ce94_0
  - r-pillar=1.10.2=r44hc72bb7e_0
  - r-pkgconfig=2.0.3=r44hc72bb7e_4
  - r-r6=2.6.1=r44hc72bb7e_0
  - r-rcolorbrewer=1.1_3=r44h785f33e_3
  - r-rlang=1.1.5=r44h93ab643_0
  - r-scales=1.3.0=r44hc72bb7e_1
  - r-tibble=3.2.1=r44hdb488b9_3
  - r-utf8=1.2.4=r44hb1dbf0f_1
  - r-vctrs=0.6.5=r44h0d4f4ea_1
  - r-viridislite=0.4.2=r44hc72bb7e_2
  - r-withr=3.0.2=r44hc72bb7e_0
  - rdflib=7.1.4=pyh29332c3_0
  - readline=8.2=h8c095d6_2
  - repoze.lru=0.7=pyhd8ed1ab_2
  - requests=2.32.3=pyhd8ed1ab_1
  - rich=14.0.0=pyh29332c3_0
  - rich-argparse=1.7.0=pyhd8ed1ab_0
  - routes=2.5.1=pyhd8ed1ab_0
  - rpsbproc=0.5.0=hd6d6fdc_3
  - ruamel.yaml=0.18.10=py39h8cd3c5a_0
  - ruamel.yaml.clib=0.2.8=py39h8cd3c5a_1
  - samtools=1.21=h96c455f_1
  - schema-salad=8.9.20250408123006=py39h8cd3c5a_0
  - sed=4.8=he412f7d_0
  - sepp=4.4.0=py39_0
  - setuptools=78.1.0=pyhff2d567_0
  - shellescape=3.4.1=py_0
  - six=1.17.0=pyhd8ed1ab_0
  - sortedcontainers=2.4.0=pyhd8ed1ab_1
  - spython=0.3.14=pyhff2d567_1
  - sqlite=3.49.1=h9eae976_2
  - suitesparse=5.10.1=h5a4f163_3
  - sysroot_linux-64=2.17=h0157908_18
  - tar=1.34=hb2e2bae_1
  - tbb=2022.1.0=h4ce085d_0
  - tk=8.6.13=noxft_h4845f30_101
  - tktable=2.10=h8bc8fbc_6
  - tomli=2.2.1=pyhd8ed1ab_1
  - tornado=6.4.2=py39h8cd3c5a_0
  - typing-extensions=4.13.1=hf5ce1d7_0
  - typing-inspection=0.4.0=pyhd8ed1ab_0
  - typing_extensions=4.13.1=pyh29332c3_0
  - tzdata=2025b=h78e105d_0
  - ucsc-fatotwobit=472=h52f6b31_1
  - ucsc-twobitinfo=472=h664eb37_1
  - unicodedata2=16.0.0=py39h8cd3c5a_0
  - urllib3=2.3.0=pyhd8ed1ab_0
  - wayland=1.23.1=h3e06ad9_0
  - webencodings=0.5.1=pyhd8ed1ab_3
  - wget=1.21.4=hda4d442_0
  - wheel=0.45.1=pyhd8ed1ab_1
  - whoosh=2.7.4=py39hf3d152e_9
  - xcb-util=0.4.1=hb711507_2
  - xcb-util-cursor=0.1.5=hb9d3cd8_0
  - xcb-util-image=0.4.0=hb711507_2
  - xcb-util-keysyms=0.4.1=hb711507_0
  - xcb-util-renderutil=0.3.10=hb711507_0
  - xcb-util-wm=0.4.2=hb711507_0
  - xkeyboard-config=2.43=hb9d3cd8_0
  - xorg-libice=1.1.2=hb9d3cd8_0
  - xorg-libsm=1.2.6=he73a12e_0
  - xorg-libx11=1.8.12=h4f16b4b_0
  - xorg-libxau=1.0.12=hb9d3cd8_0
  - xorg-libxcomposite=0.4.6=hb9d3cd8_2
  - xorg-libxcursor=1.2.3=hb9d3cd8_0
  - xorg-libxdamage=1.1.6=hb9d3cd8_0
  - xorg-libxdmcp=1.1.5=hb9d3cd8_0
  - xorg-libxext=1.3.6=hb9d3cd8_0
  - xorg-libxfixes=6.0.1=hb9d3cd8_0
  - xorg-libxi=1.8.2=hb9d3cd8_0
  - xorg-libxinerama=1.1.5=h5888daf_1
  - xorg-libxrandr=1.5.4=hb9d3cd8_0
  - xorg-libxrender=0.9.12=hb9d3cd8_0
  - xorg-libxt=1.3.1=hb9d3cd8_0
  - xorg-libxtst=1.2.5=hb9d3cd8_3
  - xorg-libxxf86vm=1.1.6=hb9d3cd8_0
  - xz=5.8.1=hbcc6ac9_0
  - xz-gpl-tools=5.8.1=hbcc6ac9_0
  - xz-tools=5.8.1=hb9d3cd8_0
  - yaml=0.2.5=h7f98852_2
  - zipp=3.21.0=pyhd8ed1ab_1
  - zipstream-new=1.1.8=pyhd8ed1ab_0
  - zlib=1.3.1=hb9d3cd8_2
  - zstandard=0.23.0=py39h8cd3c5a_1
  - zstd=1.5.7=hb8e6e7a_2
